language: python
python:
-   "3.5"
install:
-   pip install tox pylint
# python3* packages are not supported by the stock Ubuntu image Travis uses.
#-   sudo apt-get install python-matplotlib python3-matplotlib python-scipy python3-scipy python-numpy python3-numpy python-pyside python3-pyside
-   sudo apt-get install python-matplotlib python-scipy python-numpy python-pyside
script:
-   python --version
-   pylint --version
-   tox --version
-   ./pep8.sh
-   sudo apt-get install python-matplotlib
-   tox
