language: python
python:
-   2.7

virtualenv:
    system_site_packages: true

before_install:
-   sudo apt-get install -qq python-numpy python-scipy python-matplotlib

install:
-   pip install tox pylint

# Run test
script:
-   ./pep8.sh
-   tox
